name: housecat

services:
  api:
    build:
      context: ./api
      dockerfile: prod.Dockerfile
    command: gunicorn housecat.wsgi:application --bind 0.0.0:8000
    volumes:
      - ./api:/code
      - static_volume:/code/static
    ports:
      - 8000:8000
    env_file: api/.env.production

  explorer:
   build: ./explorer
   volumes:
     - ./explorer:/app
   env_file: ./explorer/.env.production
   ports:
     - 3000:3000

volumes:
  static_volume:
