name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build the API
        run: docker compose -f docker-compose.testing.yml build

      - name: Run Django tests
        run: |
          docker compose -f docker-compose.testing.yml run api python manage.py test

      - name: Build Frontend
        run: docker build -t explorer -f explorer/Dockerfile ./explorer/