name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker images
      run: |
        docker build -f api/dev.Dockerfile ./api/
        docker build -f explorer/Dockerfile ./explorer/
        docker exec python manage.py test
